### ISSUE TITLE
Error with Vietnamese text sync

### ISSUE THREAD

**Issue by gizalink** [Haravan/haravan_theme#2]
Hi author,
i'm using tool on Window 10. When sync theme from local to web haravan. There was an error with all Vietnamese text. 
Please check this error. 
Thank you so much.

**Comment by vinhhrv** [comment]
Thanks for report, we will fix soon

**Comment by lmcuong25** [comment]
hi gizalink,

Reinstall app with this command will fix your problem

All Programs -> Ruby 2.5.0 -> Start Command Prompt with Ruby

C:\Users\lublue>gem uninstall haravan_theme

C:\Users\lublue>chcp 65001

C:\Users\lublue>gem install haravan_theme
